enforce quota
cs3org/cs3apis pull request #115
Opened 2021-03-16 14:06 UTC by wkloucek

2021-03-22 12:53 UTC, labkode requested changes
@wkloucek just put the comment before the definition of the new error like the other defs.

2021-03-24 11:05 UTC, ishank011 commented
@wkloucek I can merge this, but https://github.com/cs3org/cs3apis/pull/116 has a breaking change which is implemented in reva by https://github.com/cs3org/reva/pull/1570. I'll try to get this in this week but for the time being, you can rebase your change on top of this PR. Would that be fine?

2021-03-24 12:54 UTC, wkloucek commented
@ishank011 is rebased

2021-03-24 13:38 UTC, ishank011 approved these changes

2021-03-24 13:38 UTC, merged