add TouchFile
cs3org/cs3apis pull request #154
Opened 2021-10-28 11:27 UTC by wkloucek

## Description
~`CreateFile`~ `TouchFile` can be used to create an empty file. This is the file counterpart of `CreateContainer`. It allows one to easily create a file in order to reference it with a storage and opaque id. (Referencing it with a path or a relative path is already possible without the existing file).

## Alternative considerations
One could use the `InitiateFileUpload` in order to upload a zero byte file. it will give you an array of upload methods (eg. TUS and simple) and you can then invoke the upload of the zero byte file.

This means you need an http request ( in case of the simple protocol ) in addition to the InitiateFileUpload grpc request.

To spare that http request, some file system implementations, eg the decomposedfs implement a shortcut (https://github.com/cs3org/reva/blob/4879bf6be97aecc9e30ad999355342b6ca6188f1/pkg/storage/utils/decomposedfs/upload.go#L300-L308) for zero byte files. The cs3 api client has no way to check that the upload already finishend, because there are no return codes. Therefore bugs like https://github.com/owncloud/ocis/issues/2609 arise. 
In my opinion, this shortcut for zero byte files is also wrong, because the InitiateFileUpload is only an intend to upload a file. The actual file should created when the file is finally uploaded by using the offered upload protocols (eg. simple or TUS). This also applies to zero byte files.

2021-12-02 11:25 UTC, labkode commented
@wkloucek looks good, however can you rename the method to `TouchFile`? CreateFile may imply that file contains contents and is not the case.

2021-12-02 11:33 UTC, labkode requested changes
Chang of method name to TouchFile

2021-12-09 14:39 UTC, ishank011 approved these changes

2021-12-10 10:06 UTC, refs approved these changes

2021-12-13 09:02 UTC, merged