Add an optional lock_id argument to storage methods
cs3org/cs3apis pull request #163
Opened 2022-02-09 10:10 UTC by glpatcern

Follow up of cs3org/cs3apis#162: the storage methods that modify a resource now have an optional `lock_id` argument, such that storage provider implementations can enforce the lock validation.

2022-02-09 14:26 UTC, butonic commented on cs3/storage/provider/v1beta1/provider_api.proto
> +  string lock_id = 4;
I'm not entirely sure if move/copy need a source as well as a destination lock. I'd merge like this and add another lock_id  in a subsequent PR if necessary.

2022-02-09 14:28 UTC, butonic commented on cs3/storage/provider/v1beta1/provider_api.proto
>  message UnsetArbitraryMetadataResponse {
unset also needs a lock_id parameter

2022-02-09 14:33 UTC, butonic requested changes
I think these messages also need a `lock_id`:
- [ ] CreateContainer
- [ ] TouchFile
- [ ] RestoreFileVersion
- [ ] RestoreRecycleItem

they all might end up writing into a locked resource

2022-02-09 14:48 UTC, glpatcern commented
We looked at those too:
- `CreateContainer` and `TouchFile` expect to create a resource and must fail if it exists
- Restore actions indeed may need the `lock_id` argument, going to add it

2022-02-10 09:19 UTC, glpatcern commented
I ended up adding the `lock_id` argument also to `OpenInApp`, though this is far-fetching: it would be needed when exclusive locks are implemented.

2022-02-11 09:36 UTC, glpatcern commented
@butonic not sure why I can't ask you to review again, anyway could you have another look? I'd go ahead and merge this as is, in case we can keep adding further `lock_id` arguments if we deem it needed.

2022-02-23 17:28 UTC, ishank011 commented
Can we also rename `Unlock` to `ReleaseLock`?

2022-02-23 17:31 UTC, ishank011 reviewed
For `RestoreFileVersion` and `RestoreRecycleItem`, we should specify that the lock is for the restore path

2022-02-23 17:46 UTC, glpatcern commented on cs3/storage/provider/v1beta1/provider_api.proto
> +  string lock_id = 4;
oops, fixed

2022-02-23 17:47 UTC, glpatcern commented
> Can we also rename `Unlock` to `ReleaseLock`?

As discussed, `Unlock` came from the WOPI terminology, so we leave it as is.

Otherwise, I expanded the spec for `RestoreRecycleItem`.

2022-02-23 18:17 UTC, glpatcern commented
> Should we also enforce it for `List`, since it is equivalent in case the exclusive lock is for a directory?

As a matter of fact locking a directory was not taken into account so far. I think we should put a comment that although `SetLock` supports any reference, the semantics of locked containers are not specified at this stage.

2022-02-25 08:38 UTC, ishank011 approved these changes

2022-02-25 08:38 UTC, merged